# Generated by Django 4.2.4 on 2023-08-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Script",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
