# Generated by Django 4.2.4 on 2023-08-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="passward",
            new_name="password",
        ),
    ]
