# Generated by Django 4.2.4 on 2023-08-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_rename_passward_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="script",
            name="id",
            field=models.CharField(
                max_length=32, primary_key=True, serialize=False, verbose_name="脚本ID"
            ),
        ),
    ]
